<?php

use PHPUnit\Framework\TestCase;

final class ValidatorTest extends TestCase
{
    /** @var Xylis\MailboxLayer\Validator $validator */
    protected $validator;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->validator = new Xylis\MailboxLayer\Validator('0298171f62e0037d75944220b3f3b4f9');
    }

    public function testIsValidEmailAddress()
    {
        $this->assertTrue($this->validator->validate('julien.ravia@gmail.com')->isValid());
    }

    public function testIsInvalidEmailAddress()
    {
        $this->expectException(InvalidArgumentException::class);

        $this->validator->validate('xylis@github')->isValid();
    }

    public function testIsRoleEmailAddress()
    {
        $this->assertTrue($this->validator->validate('contact@gmail.com')->isRoleEmailAddress());
    }

    public function testIsNonRoleEmailAddress()
    {
        $this->assertFalse($this->validator->validate('julien.ravia@gmail.com')->isRoleEmailAddress());
    }

    public function testIsDisposableEmailAddress()
    {
        $this->assertTrue($this->validator->validate('2837484@mailinator.com')->isDisposable());
    }

    public function testIsNonDisposableEmailAddress()
    {
        $this->assertFalse($this->validator->validate('jrgfawkes@gmail.com')->isDisposable());
    }

    public function testIsFreeDeliveredEmailAddress()
    {
        $this->assertTrue($this->validator->validate('julien.ravia@gmail.com')->isFreeDeliveredEmailAddress());
    }

    public function testIsNonFreeDeliveredEmailAddress()
    {
        $this->assertFalse($this->validator->validate('contact@julienravia.fr')->isFreeDeliveredEmailAddress());
    }
}
